config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"


  resource :profile, only: [:show, :edit, :update, :post] do
    resources :users, only: [:edit, :update]
  end

  resources :bands, only: [:index, :create, :show, :new, :edit, :update, :destroy] do
    resources :chatroom, only: :create
  end

  resources :users, only: [:update, :post, :show]

  resources :chatrooms, only: [:index, :show] do
    member do
      patch :update_user
    end
    resources :messages, only: :create
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @button_band = ""
    @banner_picture_user = @user.avatar.key

    if @user.band.present?
      @button_band = "Go to your"
      @banner_picture_user = @user.band.photo.key
    else
      @button_band = "Create a"
    end
  end

  private

  def user_params
    params.require(:user).permit(:band_id, :first_name, :last_name, :bio, :city, :instrument_id, :style_id, :video_url)
  end

  def band_params
    params.require(:user).permit(:first_name, :last_name, :bio, :city, :band_id, :photo, :avatar, :style_id,:instrument_id, :video_url)
  end
end

app/views/profiles/show.html.erb
<div class= "band-container">
  <div class="banner-band banner-user-profil">
      <%= cl_image_tag @banner_picture_user ,class: "band-banner"%>
      <h1 id="name-user"><strong><%= @user.first_name.upcase %>
      <%= @user.last_name.upcase%> </strong></h1>
  </div>
  <div class="functions-band">
  <%if @user.band.present?%>
  <%= link_to "#{@button_band} band", band_path(@user.band),  class: " btn-create-band"%>
  <%else%>
  <%= link_to "#{@button_band} band", new_band_path(),  class: " btn-create-band", data: { turbo: false }%>
  <%end%>

    <%= cl_image_tag @user.avatar.key, class: "band-avatar", width: 200, height: 200, crop: :fill, gravity: :face%>
    <div class ="user-pill d-flex justify-content-between">
    </div>
  </div>
    <div class="pills-profil-user">
      <p class= "music-style mr-2 pt-2"><%= @user.instrument.name.upcase%></p>
      <p class= "music-style pt-2"><%= @user.style.name.upcase%></p>
    </div>
    <div>
      <p class="bio-band mt-4 d-flex justify-content-space-between p-3"><%= @user.bio%></p>
    </div>
    <div class="container">
      <%if  @user.band.present? %>
        <iframe class ="d-flex m-auto" width="85%"  src="<%= @user.band.video_url%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      <%else%>
        <iframe class ="d-flex m-auto" width="85%"  src="<%= @user.video_url%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      <%end%>
    </div>
  </div>
  <%= link_to "disconnect",  destroy_user_session_path, data: {turbo_method: :delete}, class:"btn-disconnect" %>

</div>