config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"


  resource :profile, only: [:show, :edit, :update, :post] do
    resources :users, only: [:edit, :update]
  end

  resources :bands, only: [:index, :create, :show, :new, :edit, :update, :destroy] do
    resources :chatroom, only: :create
  end

  resources :users, only: [:update, :post, :show]

  resources :chatrooms, only: [:index, :show] do
    member do
      patch :update_user
    end
    resources :messages, only: :create
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :band
  has_many :messages
  has_many :users, through: :messages
  has_one :last_message, -> { last_messages }, class_name: "Message", dependent: :destroy, inverse_of: :chatroom

  # scope :unread_chatrooms, lambda { |user|
  #   subquery = Message.select("DISTINCT ON (chatroom_id) messages.*").
  #     order(:chatroom_id, id: :desc).
  #     to_sql

  #   includes(:messages, :last_message).
  #     joins("LEFT JOIN (#{subquery}) AS last_messages ON chatrooms.id = last_messages.chatroom_id").
  #     where.not("last_messages.user_id = ?", user.id).
  #     group("chatrooms.id", "last_messages.id", "last_messages.chatroom_id").
  #     order("chatrooms.id DESC")
  # }
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms_band = current_user.band_chatrooms
    @chatrooms_joined = current_user.chatrooms_joined
    @user = current_user
    @chatrooms = @user.band.chatrooms.all

  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @chatroom.messages.update_all(view: true)
    @message = Message.new
    @user = current_user
  end

  def create
    @chatroom = Chatroom.new
  end

  def update_user
    @chatroom = Chatroom.find(params[:id])
    @users = @chatroom.users
    @chatroom.name = @chatroom.band.name if @chatroom.name != @chatroom.band.name
    @user = @users.find { |user| user.band_id == nil }
    if @user.update(band: @chatroom.band)
      redirect_to chatrooms_path(@chatrooms)
    end
  end
end

app/views/chatrooms/index.html.erb
<div class="chats-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "banner.jpg"%>);">
</div>
    <%= cl_image_tag current_user.avatar.key, class: "chat-avatar", width: 200, height: 200, crop: :fill, gravity: :face%>
<div class="container container-chats">
  <div data-controller="notif-navbar">
  <div class= "chat-preview">
    <% @chatrooms_joined.each do |chatroom|%>
    <div data-action="click->notif-navbar#handleClick" data-target="message">
      <div class="message">
        <%= cl_image_tag chatroom.band.photo.key, class:"band-chat-avatar" %>
        <div class="preview">
          <h4><strong><%= link_to chatroom.band.name, chatroom_path(chatroom), class:"link-chat" %></strong></h4>
          <%= truncate(chatroom.messages.last.content, length: 20) %>
        </div>
      </div>
      </div>
    <% end %>
      <% @chatrooms_band.each do |chatroom|%>
       <div data-action="click->notif-navbar#handleClick" data-target="message">
        <div class="message">
          <% if chatroom.band.id != @user.band_id %>
            <%= cl_image_tag chatroom.band.avatar.key, class:"band-chat-avatar" %>
              <div class="preview">
                <h4><strong><%= link_to "#{chatroom.band.name}",chatroom_path(chatroom), class:"link-chat"%></strong></h4>
                <%= truncate(chatroom.messages.last.content, length: 20) %>
              </div>
          <% if chatroom.messages.last.user_id != current_user.id %>
            <div class="visible">
            </div>
            <% end %>
          <% elsif chatroom.band.id == @user.band_id && @user.id != chatroom.messages.first.user.id %>
            <%= cl_image_tag chatroom.messages.first.user.avatar.key, class:"band-chat-avatar" %>
              <div class="preview">
                <% @second_user = chatroom.messages.first.user %>
                <h4><strong><%= link_to "#{@second_user.first_name} #{@second_user.last_name}", chatroom_path(chatroom), class:"link-chat" %></strong></h4>
                <%= truncate(chatroom.messages.last.content, length: 20) %>
              </div>
            <% if chatroom.messages.last.user_id != current_user.id %>
              <div class="visible"></div>
            <% end %>
          <% elsif chatroom.band.id == @user.band_id && @user.id == chatroom.messages.first.user.id %>
            <%= cl_image_tag chatroom.band.avatar.key, class:"band-chat-avatar" %>
              <div class="preview">
                <h4><strong><%= link_to "#{chatroom.band.name}",chatroom_path(chatroom), class:"link-chat"%></strong></h4>
                <%= truncate(chatroom.messages.last.content, length: 20) %>
              </div>
                <% if chatroom.messages.last.user != current_user %>
              <div class="visible">
              </div>
            <% end %>
          </div>
          <% end %>
        </div>
        </div>
      <% end %>
</div>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="banner-dicussion-chat" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "banner.jpg"%>);">
  <% if @chatroom.band.id != @user.band_id %>
    <% if @chatroom.messages.empty? %>
      <%= link_to "#{@chatroom.band.name}",band_path(@chatroom.band), class:"title-chatroom"%>
    <% elsif @chatroom.messages.empty? == false %>
      <% @second_user = @chatroom.messages.first.user %>
      <% if @second_user.band_id != @chatroom.band_id || @second_user.band_id = nil || @user.id == @second_user.id %>
        <%= link_to "#{@chatroom.band.name}",band_path(@chatroom.band), class:"title-chatroom"%>
      <% else %>
        <%= link_to "#{@second_user.first_name} #{@second_user.last_name}", user_path(@chatroom.messages.first.user), class:"title-chatroom" %>
      <%end%>
    <% end %>
  <% elsif @chatroom.band.id == @user.band_id && @user.id != @chatroom.messages.first.user.id %>
      <% @second_user = @chatroom.messages.first.user %>
        <%= link_to "#{@second_user.first_name} #{@second_user.last_name}", user_path(@chatroom.messages.first.user), class:"title-chatroom" %>
        <%unless @chatroom.messages.first.user.band.present? %>
          <%= link_to "Add to your band", update_user_chatroom_path(@chatroom),data: {turbo_method: :patch}, class:"add-btn" %>
        <%end%>
  <% elsif @chatroom.band.id == @user.band_id && @user.id == @chatroom.messages.first.user.id%>
      <%= link_to "#{@chatroom.band.name}",band_path(@chatroom.band), class:"title-chatroom"%>
  <% end %>
    <% if current_user.band.present? %>
      <% current_user.band.id == @chatroom.band.id %>
    <% end %>

</div>
<div class="container chatroom"
    data-controller="chatroom-subscription"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
    data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">
    <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>
        <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">

          <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
            <%= render "messages/message", message: message %>
          </div>
        </div>
      <% end %>
    </div>
  <%= simple_form_for [@chatroom, @message],
    { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
  %>
  <div class="bloc-new-message">
    <%= f.input :content,
      label: false,
      placeholder: "Type your message... #{@chatroom.name}",
      wrapper_html: {class: "flex-grow-1"},
      input_html: { clss: "input-new-message"}
    %>
    <button type="submit" class="button-send-message">
      <i class="fa-solid fa-paper-plane"></i>
    </button>
  <% end %>
  </div>
</div>