config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"


  resource :profile, only: [:show, :edit, :update, :post] do
    resources :users, only: [:edit, :update]
  end

  resources :bands, only: [:index, :create, :show, :new, :edit, :update, :destroy] do
    resources :chatroom, only: :create
  end

  resources :users, only: [:update, :post, :show]

  resources :chatrooms, only: [:index, :show] do
    member do
      patch :update_user
    end
    resources :messages, only: :create
  end
end

app/models/band.rb
class Band < ApplicationRecord
  include PgSearch::Model
  has_one_attached :photo
  has_one_attached :avatar
  has_many :avatars, through: :users
  belongs_to :style
  belongs_to :needed_instrument, class_name: "Instrument"
  has_many :users
  has_many :instruments, through: :users
  has_many :chatrooms
  # Validation #
  validates :name, :bio, :city, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 3 }
  validates :bio, length: { minimum: 10 }
  pg_search_scope :search_by_name_city_and_need,
                  against: %i[name city needed_instrument_id],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    @styles = Style.all
    @instruments = Instrument.all
    @filtered_parameters = request.parameters.with_indifferent_access.slice(:style, :needed_instrument, :query)

    @bands = Band.search_by_name_city_and_need(params[:query]) if params[:query].present?
    @bands = @bands.joins(:style).where(style: { name: params[:style] }) if params[:style].present?
    @bands = @bands.joins(:needed_instrument).where(needed_instrument: { name: params[:needed_instrument] }) if params[:needed_instrument].present?
  end

  def show
    @band = Band.find(params[:id])
    @chatroom = Chatroom.joins(:messages).where(band: @band, messages: {user: current_user}).first || Chatroom.create(band: @band)
    @user = current_user
    @users = @band.users

  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    @current_user = current_user
    if @band.save
      redirect_to band_path(@band)
      current_user.update(band_id: @band.id)
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    @users = @band.users
    respond_to do |format|
      format.html { render :edit, locals: { band: @band } }
    end
  end

  def update
    @band = Band.find(params[:id])  # Assuming the user ID is passed as a parameter

    if @band.update(band_params)
      redirect_to band_path(@band)
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def band_params
    params.require(:band).permit(:name, :bio, :city, :users, :photo, :avatar, :style_id, :needed_instrument_id, :video_url)
  end
end

app/views/bands/edit.html.erb
<div class="banner-creation-band">
  <%= form_with(model: @band, url: band_path,method: :patch) do |form| %>
  <%= cl_image_tag @band.photo.key,class: "band-banner-edit"%>
    <%=cl_image_tag @band.avatar.key, class: "band-avatar-edition", width: 200, height: 200, crop: :fill%>
    <img data-target="preview.preview" style="max-width: 100%; max-height: 200px;">
    <div class="creation-picture"></div>
        <div class="custom-file-input-wrapper " data-controller="preview">
          <%= label_tag 'photo', class: 'custom-file-label-photo', id: 'photo-input' do %>
              <i class="fas fa-plus"></i>
          <% end %>
          <%= form.file_field :photo, id: 'photo', class: 'hidden-field custom-file-input', accept: 'image/png, image/jpeg, image/jpg', data: { action: 'preview#display' }%>
          <img data-preview-target="previewImage" class="photo-preview-form-edit">
        </div>
        <div class="custom-file-input-wrapper" data-controller="preview">
          <%= label_tag 'avatar', id: 'avatar-input', class: 'custom-file-label-avatar' do %>
          <i class="fas fa-plus"></i>
          <% end %>
          <%= form.file_field :avatar, id: 'avatar', class: 'hidden-field custom-file-input', accept: 'image/png, image/jpeg, image/jpg', data: { action: 'preview#display' }  %>
          <%= image_tag '' %>
          <img data-preview-target="previewImage" class="custom-avatar-input">
          <%# <img data-preview-target="preview" style="max-width: 100%; max-height: 200px;"> %>
        </div>
      <button type="button" class="btn btn-primary btn-band-show" id="edit-member-page-button" data-bs-toggle="modal" data-bs-target="#exampleModal">
          members
      </button>
    </div>
    <div class="container padding-navbar-edit">
      <div class="height-input-edition">
        <%= form.text_field :name, placeholder: 'Name', class: " input-edit-band name-band d-flex justify-content-center" %>
        <div class="name-city-edition">
          <i class="fas fa-map-marker-alt icon-page-creation" style="color: #ff082a;" ></i>
          <%= form.text_field :city, placeholder: "City", class: "input-city-edition-style" %>
        </div>
        <%= form.collection_select :needed_instrument_id, Instrument.all, :id, :name, class:"dropdown-edition", prompt: "Add the instrument you need"%>
        <%= form.collection_select :style_id, Style.all, :id, :name, prompt: "Add a style"%>
      </div>
      <%= form.text_area :bio, placeholder: "Biography", class: "bio-edit-band", input_html: {value: @band.bio }  %>
      <%# mettre le lien vidéo YOUTUBE %>
      <div class="name-input-page-edition">
        <i class="fas fa-video icon-page-creation"></i>
        <%= form.url_field :video_url, placeholder: "Video URL", class: "input-edit-url" %>
      </div>
      <%= form.submit "Save", class: "button-edition-band" %>
      <%end%>
    </div>

      <!-- POP-UP -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content pop-body">
            <button type="button" class="back-btn-pop-edit hidden-field align-self-start fas fa-arrow-left" data-bs-dismiss="modal" aria-label="Close" ></button>
          <div class="modal-header padding-modal-header align-self-center">
            <h1 class="modal-title title-member-banner" id="exampleModalLabel"  >Members</h1>
          </div>
        <%# POP-UP BODY %>
        <div class="modal-body user-names pb-5">
            <div class="member-name">
          <% @users.each do |user| %>
            <% if @users.include?(user) %>
            <div class= "name-instrument d-flex align-items-center my-4">
              <div class="">
                <div>
                  <%= button_to "DELETE",
                      user_path(user),
                      method: :patch,
                      class: "delete-button hidden-field"%>
                  <%=cl_image_tag user.avatar.key, width: 80, height: 80, crop: :fill, class: "member-photo" %>
                </div>
              </div>
              <div>
                <div class="name">
                  <%= user.first_name %>
                  <%= user.last_name %>
                </div>
                <div class= "instrument">
                  <%= user.instrument.name %>
                </div>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <%# POP-UP BODY %>
    </div>
  </div>
  </div>
</div>

app/views/bands/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "banner.jpg"%>);">
  <p class="title-band-banner">MEETSICIANS</p>
    <%= form_tag bands_path(@filtered_parameters.merge(query: params[:query])), method: :get do %>
      <div class="search-bar-black">
      <i class="fa-solid fa-magnifying-glass icon-search-bar"></i>
        <%= text_field_tag :query, params[:query], placeholder: "Search for a band or city...", class: "input-search-bands text-white"  %>
        <button type="submit" class="button-search">
          <i class="fas fa-arrow-right text-white"></i>
        </button>
      </div>
    <% end %>

  <div class="filter-search">
    <div class="oce-dropdown-container">
        <div class="oce-dropdown"  data-controller="dropdown" style="color: white">
          <input class="oce-dropdown-input" data-action="click->dropdown#toggle" placeholder="<%= params[:style] ? params[:style].capitalize : "Style" %>" readonly />
          <ul class="oce-dropdown-menu-list"  data-dropdown-target="menu" id="liste" style="display: none">
            <% @styles.each do|style| %>
              <%= link_to style.name, bands_path(@filtered_parameters.merge(style: style.name)), class:"oce-dropdown-menu-item #{'selected' if params[:style] == style.name}"%>
            <% end %>
          </ul>
        </div>
    </div>
    <div class="oce-dropdown-container-instrument">
        <div class="oce-dropdown"  data-controller="dropdown"style="color: white">
          <input class="oce-dropdown-input" data-action="click->dropdown#toggle" placeholder="<%= params[:needed_instrument] ? params[:needed_instrument].capitalize : "Instrument" %>" readonly />
          <ul class="oce-dropdown-menu-list"  data-dropdown-target="menu" id="liste" style="display: none">
            <% @instruments.each do|instrument| %>
              <%= link_to instrument.name, bands_path(@filtered_parameters.merge(needed_instrument: instrument.name)), class:"oce-dropdown-menu-item #{'selected' if params[:needed_instrument] == instrument.name}"%>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</div>

<div class="container mt-5 band-container">
  <%@bands.each do |band| %>
    <div class="card card-band mx-2 my-4 " >
      <% if band.photo.attached?%>
        <%= cl_image_tag band.photo.key, style:"height: 240px", class: "object-fit-cover"; %>
      <% else %>
        <%= cl_image_tag 'bad-omens.jpeg', alt: 'photo-default', style:"height: 240px", class: "object-fit-cover"; %>
      <% end %>
      <%= link_to band_path(band) do%>
        <div class="card-img-overlay card-band-infos d-flex flex-column align-items-center justify-content-end">
          <p class= "city-band-index position-city-in-card d-flex justify-content-center text-align-center"><i class="fa-solid fa-location-dot dot-localisation" style="color: #ff082a;"> </i> <%= band.city.upcase%></p>
          <h1 class="name-band" ><%= band.name %></h1>
          <p class="needed-instrument-pill">LOOKING FOR: <%= band.needed_instrument.name%></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%# # creer une condition: si pas de photo attaché au band, afficher une photo "neutre" %>

  <div class="footer-nav-bar">
  <%# FOOTER-NAV-BAR COMPONENT %>
  </div>
</div>

app/views/bands/new.html.erb
<div class="banner-creation-band">
  <%= form_with(model: @band, url: bands_path, local: true) do |form| %>
  <img data-target="preview.preview" style="max-width: 100%; max-height: 200px;">
  <div class="creation-picture"></div>
    <div class="custom-file-input-wrapper " data-controller="preview">
      <%= label_tag 'photo', class: 'custom-file-label', id: 'photo-input' do %>
          <i class="fas fa-plus"></i>
      <% end %>
      <%= form.file_field :photo, id: 'photo', class: 'hidden-field custom-file-input', accept: 'image/png, image/jpeg, image/jpg', data: { action: 'preview#display' }%>
      <img data-preview-target="previewImage" class="photo-preview-form">
    </div>
    <div class="custom-file-input-wrapper" data-controller="preview">
      <%= label_tag 'avatar', id: 'avatar-input', class: 'custom-file-label' do %>
        <i class="fas fa-plus"></i>
      <% end %>
      <%= form.file_field :avatar, id: 'avatar', class: 'hidden-field custom-file-input', accept: 'image/png, image/jpeg, image/jpg', data: { action: 'preview#display' }  %>
      <%= image_tag '' %>
      <img data-preview-target="previewImage" class="avatar-preview-form">
      <%# <img data-preview-target="preview" style="max-width: 100%; max-height: 200px;"> %>
    </div>
  </div>
  <div class="container padding-navbar-edit">
  <div class="padding-form-creation">
  <div class="name-input-page-creation">
    <i class="far fa-user-circle icon-page-creation"></i>
    <%= form.text_field :name, placeholder: 'Name', class: " input-creation-style " %>
  </div>
  <div class="name-input-page-creation">
    <i class="fas fa-pen pen-input"></i>
    <%= form.text_area :bio, placeholder: "Biography", class: "input-creation-style" %>
  </div>
  <div class="name-input-page-creation">
    <i class="fas fa-map-marker-alt icon-page-creation"></i>
    <%= form.text_field :city, placeholder: "City", class: "input-creation-style" %>
  </div>
  <div class="name-input-page-creation">
    <i class="fas fa-video icon-page-creation"></i>
    <%= form.url_field :video_url, placeholder: "Video URL", class: "input-creation-style" %>
  </div>
    <%= form.collection_select :needed_instrument_id, Instrument.all, :id, :name, prompt: "Add the instrument you need"%>
    <%= form.collection_select :style_id, Style.all, :id, :name, prompt: "Add a style"%>
    <%= form.submit "Create Band", class: "button-creation-band" %>
    <% end %>
  </div>
<%# <script src="/path/to/preview_controller.js" type="module"></script> %>
</div>

app/views/bands/show.html.erb
<div class= "band-container">
  <div class="banner-band">
    <% if @band.photo.attached?%>
      <%= cl_image_tag @band.photo.key,class: "band-banner"%>
    <% else %>
      <%= cl_image_tag 'bad-omens.jpeg', alt: 'photo-default', style:"width: 400px"; %>

    <% end %>
  </div>
    <p class= "need-instrument-band d-flex justify-content-center">LOOKING FOR : <%= @band.needed_instrument.name.upcase%></p>
    <p class= "city-band position-city d-flex justify-content-center text-align-center"><i class="fa-solid fa-location-dot dot-localisation padding-dot" style="color: #ff082a;"> </i> <%= @band.city.upcase%></p>
    <%if @users.include?(@user) %>
      <%= link_to "",edit_band_path(@band),  class: "custom-edition-profil", data: { turbo: false }%>
    <% end %>
  <div class="functions-band"><%# !!!!!!!!!! PATH DU LINK_TO A CHANGER !!!!!!!!!!!!%>
      <!-- BTN MEMBERS = POP-UP -->
    <button type="button" class="btn btn-primary btn-band-show" data-bs-toggle="modal" data-bs-target="#exampleModal">
      members
    </button>
    <% if @band.avatar.attached?%>
      <%=cl_image_tag @band.avatar.key, class: "band-avatar", width: 200, height: 200, crop: :fill%>
    <% else %>
      <%= cl_image_tag 'bad-omens.jpeg', class: 'photo-default'%>
    <% end %>

    <%unless @users.include?(@user) %>
      <%= link_to "contact", chatroom_path(@chatroom), class:"contact btn-band-show" %>
    <% end %>

    <!-- POP-UP -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content pop-body">
            <button type="button" class="back-btn-pop-edit hidden-field align-self-start fas fa-arrow-left" data-bs-dismiss="modal" aria-label="Close" ></button>
          <div class="modal-header align-self-center padding-modal-header">
            <h1 class="modal-title title-member-banner" id="exampleModalLabel"  >Members</h1>
          </div>

          <%# POP-UP BODY %>
          <div class="modal-body user-names pb-5">
            <div class="member-name">
              <% @users.each do |user| %>
                <div class= "name-instrument d-flex align-items-center my-4 ">
                  <div>
                    <%=cl_image_tag user.avatar.key, width: 80, height: 80, crop: :fill, class: "member-photo", gravity: :face %>
                  </div>
                  <div>
                    <div class="name">
                      <%= user.first_name %>
                      <%= user.last_name %>
                    </div>
                    <div class= "instrument">
                      <%= user.instrument.name %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <%# POP-UP BODY %>
        </div>
      </div>
    </div>
  </div>
  <div>
    <h1 class="name-band d-flex justify-content-center pt-4"><%= @band.name.upcase%> </h1>
    <p class= "music-style d-flex justify-content-center pt-2"><%= @band.style.name.upcase%></p>
    <p class="bio-band d-flex justify-content-space-between p-3"><%= @band.bio%></p>
    <%# mettre le lien vidéo YOUTUBE %>
    <iframe class ="d-flex m-auto" width="85%"  src="<%= @band.video_url%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  </div>
</div>